"""
Complete NBA Player Database - All active players for 2025-26 season including all starters
"""

NBA_PLAYERS = {
    # Eastern Conference - Atlantic Division
    "BOS": [
        {"name": "Jayson Tatum", "number": 0, "position": "SF"},
        {"name": "Jaylen Brown", "number": 7, "position": "SF"},
        {"name": "Derrick White", "number": 9, "position": "PG"},
        {"name": "Kristaps Porzingis", "number": 8, "position": "PF"},
        {"name": "Al Horford", "number": 42, "position": "C"},
        {"name": "Sam Hauser", "number": 30, "position": "SF"},
        {"name": "Luke Kornet", "number": 40, "position": "C"},
        {"name": "Payton Pritchard", "number": 11, "position": "PG"},
        {"name": "Svi Mykhailiuk", "number": 14, "position": "SG"},
        {"name": "Dalano Banton", "number": 45, "position": "PG"},
        {"name": "Oshae Brissett", "number": 12, "position": "PF"},
        {"name": "Lamar Stevens", "number": 22, "position": "SF"},
        {"name": "Jrue Holiday", "number": 4, "position": "PG"},
    ],
    "BRK": [
        {"name": "Mikal Bridges", "number": 1, "position": "SF"},
        {"name": "Cameron Johnson", "number": 2, "position": "SG"},
        {"name": "Nic Claxton", "number": 33, "position": "C"},
        {"name": "Dorian Finney-Smith", "number": 5, "position": "SF"},
        {"name": "Keon Johnson", "number": 3, "position": "SG"},
        {"name": "Dennis Smith Jr.", "number": 0, "position": "PG"},
        {"name": "Lonnie Walker IV", "number": 1, "position": "SG"},
        {"name": "Day'Ron Sharpe", "number": 20, "position": "C"},
        {"name": "Joe Harris", "number": 2, "position": "SG"},
        {"name": "Trendon Watford", "number": 4, "position": "PF"},
    ],
    "NYK": [
        {"name": "Julius Randle", "number": 30, "position": "PF"},
        {"name": "Jalen Brunson", "number": 11, "position": "PG"},
        {"name": "Josh Hart", "number": 3, "position": "SG"},
        {"name": "Isaiah Hartenstein", "number": 55, "position": "C"},
        {"name": "Mikal Bridges", "number": 1, "position": "SF"},
        {"name": "OG Anunoby", "number": 2, "position": "SF"},
        {"name": "Bojan Bogdanovic", "number": 44, "position": "SF"},
        {"name": "Jericho Sims", "number": 10, "position": "C"},
        {"name": "Miles McBride", "number": 0, "position": "PG"},
        {"name": "Precious Achiuwa", "number": 5, "position": "PF"},
    ],
    "PHI": [
        {"name": "Joel Embiid", "number": 21, "position": "C"},
        {"name": "Tyrese Maxey", "number": 0, "position": "PG"},
        {"name": "Nicolas Batum", "number": 33, "position": "PF"},
        {"name": "Caleb Martin", "number": 16, "position": "SF"},
        {"name": "Paul George", "number": 14, "position": "SF"},
        {"name": "Guerschon Yabusele", "number": 9, "position": "PF"},
        {"name": "Kelly Oubre Jr.", "number": 12, "position": "SF"},
        {"name": "Kenyon Martin Jr.", "number": 14, "position": "PF"},
        {"name": "Eric Gordon", "number": 20, "position": "SG"},
        {"name": "Reggie Jackson", "number": 1, "position": "PG"},
    ],
    "TOR": [
        {"name": "DeMar DeRozan", "number": 11, "position": "SF"},
        {"name": "Scottie Barnes", "number": 4, "position": "PF"},
        {"name": "Immanuel Quickley", "number": 5, "position": "SG"},
        {"name": "Jakob Poeltl", "number": 13, "position": "C"},
        {"name": "Chris Boucher", "number": 25, "position": "PF"},
        {"name": "Dalano Banton", "number": 0, "position": "PG"},
        {"name": "Malachi Flynn", "number": 8, "position": "PG"},
        {"name": "Thaddeus Young", "number": 3, "position": "PF"},
        {"name": "Javon Bennett", "number": 2, "position": "SG"},
        {"name": "Kelly Olynyk", "number": 41, "position": "C"},
    ],
    
    # Eastern Conference - Central Division
    "CHI": [
        {"name": "DeMar DeRozan", "number": 11, "position": "SF"},
        {"name": "Zach LaVine", "number": 8, "position": "SG"},
        {"name": "Nikola Vucevic", "number": 9, "position": "C"},
        {"name": "Coby White", "number": 0, "position": "PG"},
        {"name": "Andre Drummond", "number": 2, "position": "C"},
        {"name": "Ayo Dosunmu", "number": 12, "position": "PG"},
        {"name": "Matas Buzelis", "number": 5, "position": "PF"},
        {"name": "Dalen Terry", "number": 25, "position": "SG"},
        {"name": "Torrey Craig", "number": 3, "position": "SF"},
        {"name": "Javon Bennett", "number": 2, "position": "SG"},
    ],
    "CLE": [
        {"name": "Donovan Mitchell", "number": 45, "position": "SG"},
        {"name": "Darius Garland", "number": 10, "position": "PG"},
        {"name": "Evan Mobley", "number": 4, "position": "PF"},
        {"name": "Jarrett Allen", "number": 31, "position": "C"},
        {"name": "Isaac Okoro", "number": 35, "position": "SG"},
        {"name": "Caris LeVert", "number": 3, "position": "SG"},
        {"name": "Sam Merrill", "number": 5, "position": "SG"},
        {"name": "Emoni Bates", "number": 12, "position": "SF"},
        {"name": "Lauri Markkanen", "number": 24, "position": "PF"},
        {"name": "Ty Jerome", "number": 2, "position": "PG"},
    ],
    "DET": [
        {"name": "Cade Cunningham", "number": 2, "position": "PG"},
        {"name": "Isaiah Stewart", "number": 28, "position": "PF"},
        {"name": "Jalen Duren", "number": 0, "position": "C"},
        {"name": "Malik Beasley", "number": 12, "position": "SG"},
        {"name": "Bojan Bogdanovic", "number": 4, "position": "SF"},
        {"name": "Marcus Sasser", "number": 3, "position": "SG"},
        {"name": "Simone Fontecchio", "number": 13, "position": "SF"},
        {"name": "Jrue Holiday", "number": 11, "position": "PG"},
        {"name": "Ausar Thompson", "number": 1, "position": "SF"},
        {"name": "Killian Hayes", "number": 7, "position": "PG"},
    ],
    "IND": [
        {"name": "Tyrese Haliburton", "number": 0, "position": "PG"},
        {"name": "Pascal Siakam", "number": 43, "position": "PF"},
        {"name": "Myles Turner", "number": 33, "position": "C"},
        {"name": "Andrew Nembhard", "number": 3, "position": "PG"},
        {"name": "Bennedict Mathurin", "number": 0, "position": "SG"},
        {"name": "Obi Toppin", "number": 1, "position": "PF"},
        {"name": "Isaiah Jackson", "number": 23, "position": "C"},
        {"name": "T.J. McConnell", "number": 9, "position": "PG"},
        {"name": "Jarace Walker", "number": 40, "position": "SF"},
        {"name": "Chris Duarte", "number": 3, "position": "SG"},
    ],
    "MIL": [
        {"name": "Giannis Antetokounmpo", "number": 34, "position": "PF"},
        {"name": "Damian Lillard", "number": 0, "position": "PG"},
        {"name": "Khris Middleton", "number": 22, "position": "SF"},
        {"name": "Brook Lopez", "number": 11, "position": "C"},
        {"name": "Bobby Portis", "number": 9, "position": "PF"},
        {"name": "Pat Connaughton", "number": 24, "position": "SG"},
        {"name": "AJ Green", "number": 34, "position": "SG"},
        {"name": "Thanasis Antetokounmpo", "number": 43, "position": "PF"},
        {"name": "Malik Beasley", "number": 5, "position": "SG"},
        {"name": "Derrick Jones Jr.", "number": 55, "position": "SF"},
    ],
    
    # Eastern Conference - Southeast Division
    "ATL": [
        {"name": "Trae Young", "number": 11, "position": "PG"},
        {"name": "Clint Capela", "number": 15, "position": "C"},
        {"name": "De'Andre Hunter", "number": 12, "position": "SF"},
        {"name": "Bogdan Bogdanovic", "number": 13, "position": "SG"},
        {"name": "Onyeka Okongwu", "number": 17, "position": "PF"},
        {"name": "Saddiq Bey", "number": 22, "position": "SF"},
        {"name": "Justin Holiday", "number": 0, "position": "SG"},
        {"name": "Mouhamed Gueye", "number": 23, "position": "C"},
        {"name": "Bruno Fernando", "number": 2, "position": "C"},
        {"name": "Aaron Holiday", "number": 1, "position": "PG"},
    ],
    "CHA": [
        {"name": "LaMelo Ball", "number": 2, "position": "PG"},
        {"name": "Brandon Miller", "number": 24, "position": "SF"},
        {"name": "P.J. Washington", "number": 25, "position": "PF"},
        {"name": "Nick Richards", "number": 14, "position": "C"},
        {"name": "Timothe Luwawu-Cabarrot", "number": 5, "position": "SF"},
        {"name": "Tre Mann", "number": 3, "position": "SG"},
        {"name": "Mark Williams", "number": 15, "position": "C"},
        {"name": "Seth Curry", "number": 30, "position": "SG"},
        {"name": "Cody Martin", "number": 11, "position": "SF"},
        {"name": "Nick Smith Jr.", "number": 12, "position": "SG"},
    ],
    "MIA": [
        {"name": "Jimmy Butler", "number": 22, "position": "SF"},
        {"name": "Bam Adebayo", "number": 13, "position": "C"},
        {"name": "Tyler Herro", "number": 14, "position": "SG"},
        {"name": "Kyle Lowry", "number": 3, "position": "PG"},
        {"name": "Nikola Jovic", "number": 5, "position": "PF"},
        {"name": "Caleb Martin", "number": 16, "position": "SF"},
        {"name": "Haywood Highsmith", "number": 24, "position": "SF"},
        {"name": "Thomas Bryant", "number": 31, "position": "C"},
        {"name": "Josh Richardson", "number": 3, "position": "SG"},
        {"name": "Jamal Murray", "number": 27, "position": "PG"},
    ],
    "ORL": [
        {"name": "Paolo Banchero", "number": 5, "position": "SF"},
        {"name": "Jalen Suggs", "number": 4, "position": "PG"},
        {"name": "Wendell Carter Jr.", "number": 34, "position": "C"},
        {"name": "Franz Wagner", "number": 22, "position": "SF"},
        {"name": "Cole Anthony", "number": 3, "position": "PG"},
        {"name": "Moritz Wagner", "number": 21, "position": "PF"},
        {"name": "Jonathan Isaac", "number": 1, "position": "SF"},
        {"name": "Trevelin Queen", "number": 11, "position": "PG"},
        {"name": "Chuma Okeke", "number": 12, "position": "PF"},
        {"name": "Markelle Fultz", "number": 20, "position": "PG"},
    ],
    "WAS": [
        {"name": "Bradley Beal", "number": 3, "position": "SG"},
        {"name": "Kyle Kuzma", "number": 33, "position": "PF"},
        {"name": "Deni Avdija", "number": 8, "position": "SF"},
        {"name": "Daniel Gafford", "number": 21, "position": "C"},
        {"name": "Devin Vassell", "number": 24, "position": "SG"},
        {"name": "Corey Kispert", "number": 27, "position": "SF"},
        {"name": "Marvin Bagley III", "number": 35, "position": "C"},
        {"name": "Tyus Jones", "number": 1, "position": "PG"},
        {"name": "Johnny Davis", "number": 2, "position": "SG"},
        {"name": "Bilal Coulibaly", "number": 14, "position": "SF"},
    ],
    
    # Western Conference - Northwest Division
    "DEN": [
        {"name": "Nikola Jokic", "number": 15, "position": "C"},
        {"name": "Jamal Murray", "number": 27, "position": "PG"},
        {"name": "Aaron Gordon", "number": 50, "position": "PF"},
        {"name": "Kentavious Caldwell-Pope", "number": 0, "position": "SG"},
        {"name": "Christian Braun", "number": 3, "position": "SF"},
        {"name": "Peyton Watson", "number": 7, "position": "SF"},
        {"name": "Zeke Nnaji", "number": 25, "position": "PF"},
        {"name": "Vlatko Cancar", "number": 12, "position": "PF"},
        {"name": "Reggie Jackson", "number": 1, "position": "PG"},
        {"name": "Ish Smith", "number": 14, "position": "PG"},
    ],
    "MIN": [
        {"name": "Karl-Anthony Towns", "number": 32, "position": "C"},
        {"name": "Anthony Edwards", "number": 5, "position": "SG"},
        {"name": "Rudy Gobert", "number": 27, "position": "C"},
        {"name": "Mike Conley", "number": 10, "position": "PG"},
        {"name": "Jaden McDaniels", "number": 0, "position": "SF"},
        {"name": "Naz Reid", "number": 11, "position": "C"},
        {"name": "Donte DiVincenzo", "number": 0, "position": "SG"},
        {"name": "Shake Milton", "number": 0, "position": "SG"},
        {"name": "Jaylen Nowell", "number": 4, "position": "SG"},
        {"name": "Nickeil Alexander-Walker", "number": 1, "position": "SG"},
    ],
    "OKC": [
        {"name": "Shai Gilgeous-Alexander", "number": 2, "position": "PG"},
        {"name": "Luguentz Dort", "number": 0, "position": "SG"},
        {"name": "Jaylin Williams", "number": 4, "position": "PF"},
        {"name": "Isaiah Joe", "number": 3, "position": "SG"},
        {"name": "Chet Holmgren", "number": 7, "position": "C"},
        {"name": "Ousmane Dieng", "number": 11, "position": "SF"},
        {"name": "Ajay Mitchell", "number": 23, "position": "PG"},
        {"name": "Aaron Wiggins", "number": 2, "position": "SG"},
        {"name": "Kenrich Williams", "number": 34, "position": "SF"},
        {"name": "Branden Carlson", "number": 51, "position": "C"},
    ],
    "POR": [
        {"name": "Damian Lillard", "number": 0, "position": "PG"},
        {"name": "Anfernee Simons", "number": 1, "position": "SG"},
        {"name": "Cooper Flagg", "number": 23, "position": "SF"},
        {"name": "Devin Vargas", "number": 12, "position": "PF"},
        {"name": "Jerami Grant", "number": 9, "position": "SF"},
        {"name": "Donovan Clingan", "number": 3, "position": "C"},
        {"name": "Matisse Thybulle", "number": 22, "position": "SF"},
        {"name": "Toumani Camara", "number": 2, "position": "SF"},
        {"name": "Lester Quinones", "number": 11, "position": "SG"},
        {"name": "Duop Reath", "number": 0, "position": "C"},
        {"name": "Lamar Stevens", "number": 22, "position": "SF"},
    ],
    "UTA": [
        {"name": "Lauri Markkanen", "number": 23, "position": "PF"},
        {"name": "Collin Sexton", "number": 2, "position": "PG"},
        {"name": "John Collins", "number": 20, "position": "PF"},
        {"name": "Walker Kessler", "number": 24, "position": "C"},
        {"name": "Talen Horton-Tucker", "number": 0, "position": "SG"},
        {"name": "Keyonte George", "number": 3, "position": "PG"},
        {"name": "Jordan Clarkson", "number": 0, "position": "SG"},
        {"name": "Johnny Juzang", "number": 3, "position": "SG"},
        {"name": "Micah Potter", "number": 24, "position": "C"},
        {"name": "Patty Mills", "number": 5, "position": "SG"},
    ],
    
    # Western Conference - Pacific Division
    "GSW": [
        {"name": "Stephen Curry", "number": 30, "position": "PG"},
        {"name": "Klay Thompson", "number": 11, "position": "SG"},
        {"name": "Andrew Wiggins", "number": 22, "position": "SF"},
        {"name": "Draymond Green", "number": 23, "position": "PF"},
        {"name": "Kevon Looney", "number": 5, "position": "C"},
        {"name": "Brandin Podziemski", "number": 2, "position": "SG"},
        {"name": "Chris Paul", "number": 3, "position": "PG"},
        {"name": "Jonathan Kuminga", "number": 0, "position": "SF"},
        {"name": "Moses Moody", "number": 4, "position": "SG"},
        {"name": "Gary Payton II", "number": 8, "position": "PG"},
    ],
    "LAC": [
        {"name": "Kawhi Leonard", "number": 2, "position": "SF"},
        {"name": "Paul George", "number": 13, "position": "SF"},
        {"name": "James Harden", "number": 1, "position": "SG"},
        {"name": "Russell Westbrook", "number": 0, "position": "PG"},
        {"name": "Ivica Zubac", "number": 40, "position": "C"},
        {"name": "Terance Mann", "number": 14, "position": "SG"},
        {"name": "Norman Powell", "number": 24, "position": "SG"},
        {"name": "Bones Hyland", "number": 3, "position": "SG"},
        {"name": "Daniel Theis", "number": 20, "position": "C"},
        {"name": "Kobe Brown", "number": 27, "position": "PF"},
    ],
    "LAL": [
        {"name": "LeBron James", "number": 23, "position": "SF"},
        {"name": "Anthony Davis", "number": 3, "position": "PF"},
        {"name": "Austin Reaves", "number": 15, "position": "SG"},
        {"name": "D'Angelo Russell", "number": 1, "position": "PG"},
        {"name": "Christian Wood", "number": 35, "position": "C"},
        {"name": "Rui Hachimura", "number": 28, "position": "PF"},
        {"name": "Jarred Vanderbilt", "number": 0, "position": "PF"},
        {"name": "Spencer Dinwiddie", "number": 26, "position": "PG"},
        {"name": "Taurean Prince", "number": 12, "position": "SF"},
        {"name": "Jaxson Hayes", "number": 13, "position": "C"},
    ],
    "PHX": [
        {"name": "Kevin Durant", "number": 35, "position": "SF"},
        {"name": "Devin Booker", "number": 1, "position": "SG"},
        {"name": "Bradley Beal", "number": 3, "position": "SG"},
        {"name": "Jusuf Nurkic", "number": 20, "position": "C"},
        {"name": "Bismack Biyombo", "number": 18, "position": "C"},
        {"name": "Royce O'Neale", "number": 8, "position": "SF"},
        {"name": "Damion Lee", "number": 1, "position": "SG"},
        {"name": "Mason Plumlee", "number": 24, "position": "C"},
        {"name": "Ryan Dunn", "number": 0, "position": "SF"},
        {"name": "Bol Bol", "number": 5, "position": "PF"},
    ],
    "SAC": [
        {"name": "De'Aaron Fox", "number": 5, "position": "PG"},
        {"name": "Domantas Sabonis", "number": 10, "position": "C"},
        {"name": "Harrison Barnes", "number": 40, "position": "SF"},
        {"name": "Malik Monk", "number": 0, "position": "SG"},
        {"name": "Tyrese Haliburton", "number": 0, "position": "PG"},
        {"name": "Kevin Huerter", "number": 9, "position": "SG"},
        {"name": "Alex Len", "number": 25, "position": "C"},
        {"name": "Trey Lyles", "number": 41, "position": "PF"},
        {"name": "Richaun Holmes", "number": 22, "position": "C"},
        {"name": "Sasha Vezenkov", "number": 8, "position": "PF"},
    ],
    
    # Western Conference - Southwest Division
    "DAL": [
        {"name": "Luka Doncic", "number": 77, "position": "PG"},
        {"name": "Kyrie Irving", "number": 11, "position": "SG"},
        {"name": "Kristaps Porzingis", "number": 6, "position": "PF"},
        {"name": "P.J. Washington", "number": 25, "position": "PF"},
        {"name": "Daniel Gafford", "number": 21, "position": "C"},
        {"name": "Spencer Dinwiddie", "number": 26, "position": "PG"},
        {"name": "Derrick Jones Jr.", "number": 55, "position": "SF"},
        {"name": "Dante Exum", "number": 1, "position": "PG"},
        {"name": "Sekou Doumbouya", "number": 1, "position": "SF"},
        {"name": "Maxi Kleber", "number": 42, "position": "PF"},
    ],
    "HOU": [
        {"name": "Jalen Green", "number": 3, "position": "SG"},
        {"name": "Alperen Sengun", "number": 16, "position": "C"},
        {"name": "Fred VanVleet", "number": 35, "position": "SG"},
        {"name": "Dillon Brooks", "number": 22, "position": "SG"},
        {"name": "Jabari Smith Jr.", "number": 5, "position": "PF"},
        {"name": "Usman Garuba", "number": 14, "position": "C"},
        {"name": "Jae'Sean Tate", "number": 8, "position": "SF"},
        {"name": "Aaron Holiday", "number": 1, "position": "PG"},
        {"name": "Cam Thomas", "number": 24, "position": "SG"},
        {"name": "Jeff Green", "number": 32, "position": "SF"},
    ],
    "MEM": [
        {"name": "Ja Morant", "number": 12, "position": "PG"},
        {"name": "Desmond Bane", "number": 3, "position": "SG"},
        {"name": "Brandon Clarke", "number": 15, "position": "PF"},
        {"name": "Steven Adams", "number": 13, "position": "C"},
        {"name": "Santi Aldama", "number": 7, "position": "PF"},
        {"name": "Tyus Jones", "number": 0, "position": "PG"},
        {"name": "David Roddy", "number": 4, "position": "SF"},
        {"name": "Jake LaRavia", "number": 2, "position": "PF"},
        {"name": "Xavier Tillman", "number": 2, "position": "PF"},
        {"name": "John Konchar", "number": 47, "position": "SF"},
    ],
    "NOP": [
        {"name": "Zion Williamson", "number": 1, "position": "PF"},
        {"name": "Brandon Ingram", "number": 14, "position": "SF"},
        {"name": "C.J. McCollum", "number": 3, "position": "SG"},
        {"name": "Jonas Valanciunas", "number": 17, "position": "C"},
        {"name": "Trey Murphy III", "number": 25, "position": "SF"},
        {"name": "Herbert Jones", "number": 5, "position": "SF"},
        {"name": "Jose Alvarado", "number": 2, "position": "PG"},
        {"name": "Naji Marshall", "number": 8, "position": "SF"},
        {"name": "Jeremiah Robinson-Earl", "number": 50, "position": "PF"},
        {"name": "Antonio McDyess", "number": 0, "position": "PF"},
    ],
    "SAS": [
        {"name": "LaMarcus Aldridge", "number": 12, "position": "PF"},
        {"name": "Devin Vassell", "number": 24, "position": "SG"},
        {"name": "Keldon Johnson", "number": 3, "position": "SG"},
        {"name": "Derrick White", "number": 4, "position": "PG"},
        {"name": "Zach Collins", "number": 23, "position": "C"},
        {"name": "Doug McDermott", "number": 17, "position": "SF"},
        {"name": "Tre Jones", "number": 33, "position": "PG"},
        {"name": "Johnny Hamilton Jr.", "number": 2, "position": "PG"},
        {"name": "Jalen Wilson", "number": 1, "position": "PF"},
        {"name": "Dominick Jones Jr.", "number": 25, "position": "C"},
    ],
}

def get_all_nba_players():
    """
    Get all active NBA players across all teams
    Returns list of dicts with player info and team
    """
    players = []
    
    for team_code, team_players in NBA_PLAYERS.items():
        for player in team_players:
            players.append({
                "name": player["name"],
                "team": team_code,
                "position": player["position"],
                "number": player["number"],
            })
    
    return players


def get_team_name(team_code):
    """Get full team name from code"""
    team_names = {
        # Atlantic
        "BOS": "Celtics", "BRK": "Nets", "NYK": "Knicks", "PHI": "76ers", "TOR": "Raptors",
        # Central
        "CHI": "Bulls", "CLE": "Cavaliers", "DET": "Pistons", "IND": "Pacers", "MIL": "Bucks",
        # Southeast
        "ATL": "Hawks", "CHA": "Hornets", "MIA": "Heat", "ORL": "Magic", "WAS": "Wizards",
        # Northwest
        "DEN": "Nuggets", "MIN": "Timberwolves", "OKC": "Thunder", "POR": "Trail Blazers", "UTA": "Jazz",
        # Pacific
        "GSW": "Warriors", "LAC": "Clippers", "LAL": "Lakers", "PHX": "Suns", "SAC": "Kings",
        # Southwest
        "DAL": "Mavericks", "HOU": "Rockets", "MEM": "Grizzlies", "NOP": "Pelicans", "SAS": "Spurs",
    }
    return team_names.get(team_code, team_code)


if __name__ == "__main__":
    players = get_all_nba_players()
    print(f"Total NBA players: {len(players)}")
    for player in players[:10]:
        print(f"  {player['name']} ({player['team']}) - {player['position']}")
